### ISSUE TITLE
reconnect on API_AUTHORIZATION_TIMEOUT

### ISSUE THREAD

**Issue by lewyobsdlpx** [delphix/msksidekick#13]
**Is your feature request related to a problem? Please describe.**
When executing a full offline backup, customer hits API_AUTHORIZATION_TIMEOUT (normally 60 minutes).

**Describe the solution you'd like**
When the masking API_AUTHORIZATION_TIMEOUT is hit, msk-sidekick needs to detect the disconnet, then reconnect, and continue with the outstanding tasks.

**Describe alternatives you've considered**
We tried extending the default timeout; however, this neither allowed the full backup to complete, nor did the support intervention required to apply the work-around scale to a general solution.

**Comment by ajaytho** [comment]
Feature added in v2.0.8. Latest version is v2.0.8.5
