### ISSUE TITLE
"December 8th 2022: Not able to sync global objects"

### ISSUE THREAD

**Issue by carloscuellar87d** [delphix/msksidekick#23]
** Expected Behavior**
msksidekick sync-globalobj should be able to sync global objects between Delphix Masking engines

** Actual Behavior**
msksidekick sync-globalobj failed with the following error:

                                     Masking Sidekick - 2.0.8.2
****************************************************************************************************
 Error connecting source engine engine1
 Error connecting source engine engine1
 Error connecting source engine engine1

**Steps To Reproduce the Problem**
To run a command similar to:

/msksidekick sync-globalobj --srcmskengname engine1 --tgtmskengname engine2 -g -u admin -p ***--protocol http

**Version**
This is happening with msksidekick 2.0.8 and 2.0.8.2. However, this works in 2.0.7.
Tested with Delphix Masking engines version 6.0.15, 6.0.16 and 6.0.17.2

**Comment by carloscuellar87d** [comment]
This is the expected output(using 2.0.7 sidekick version):

./msksidekick sync-globalobj --srcmskengname engine1 --tgtmskengname engine2 -g -u admin -p *** --protocol http

                                      Masking Sidekick - 2.0.7
****************************************************************************************************
 Syncable Object GLOBAL_OBJECT synced successfully.

**Comment by ajaytho** [comment]
Feature added in v2.0.8.5
