### ISSUE TITLE
"Aug 23rd 2023 - To obfuscate passwords when exporting masking users"

### ISSUE THREAD

**Issue by carloscuellar87d** [delphix/msksidekick#27]
** Expected Behavior**
When users are exported into dat files, no passwords should be displayed inside of those files.

** Actual Behavior**
When users are exported into dat files, a generic passwords is displayed inside of those files which could lead to having security concerns.

**Steps To Reproduce the Problem**
carlos.cuellar@Carlos-Alejandro-Cuellar-Macias-MacBook-Pro  ~/Documents/msksidekick/2.0.8  ./msksidekick offline-backup-eng --mskengname [dxcarcc02.dcol2.delphix.com](http://dxcarcc02.dcol2.delphix.com/) --backup_dir /Users/carlos.cuellar/Documents/msksidekick/2.0.8/ -u admin -p *** --protocol http

                                      Masking Sidekick - 2.0.8
****************************************************************************************************
 Login Successful.
Created directory structure for backups

Created backup of syncable_object_type GLOBAL_OBJECT
Created backup of syncable_object_type FILE_FORMAT
Created backup of syncable_object_type FILE_FORMAT
Created backup of syncable_object_type FILE_FORMAT
Created backup of syncable_object_type FILE_FORMAT
Created backup of syncable_object_type FILE_FORMAT
Created backup of syncable_object_type FILE_FORMAT
Created backup of syncable_object_type FILE_FORMAT
Created backup of syncable_object_type FILE_FORMAT

Created backup of role All Privileges
Created mapping file for roles

Created backup of user admin
Created backup of user carlos

Created backup of otf_job_mapping

Created backup of environment ENV01
Created backup of environment ENV02
Created backup of environment ENV1
Created mapping file for environment

Created backup of masking engine at /Users/carlos.cuellar/Documents/msksidekick/2.0.8/08222023_173726

 carlos.cuellar@Carlos-Alejandro-Cuellar-Macias-MacBook-Pro  ~/Documents/msksidekick/2.0.8  cd /Users/carlos.cuellar/Documents/msksidekick/2.0.8/08222023_173726
 carlos.cuellar@Carlos-Alejandro-Cuellar-Macias-MacBook-Pro  ~/Documents/msksidekick/2.0.8/08222023_173726  ls -lrth
total 0
drwxr-xr-x  2 carlos.cuellar  staff    64B Aug 22 17:37 applications
drwxr-xr-x  4 carlos.cuellar  staff   128B Aug 22 17:38 globalobjects
drwxr-xr-x  3 carlos.cuellar  staff    96B Aug 22 17:38 roleobjects
drwxr-xr-x  4 carlos.cuellar  staff   128B Aug 22 17:38 userobjects
drwxr-xr-x  5 carlos.cuellar  staff   160B Aug 22 17:39 environments
drwxr-xr-x  5 carlos.cuellar  staff   160B Aug 22 17:39 mappings
 carlos.cuellar@Carlos-Alejandro-Cuellar-Macias-MacBook-Pro  ~/Documents/msksidekick/2.0.8/08222023_173726  cd userobjects
 carlos.cuellar@Carlos-Alejandro-Cuellar-Macias-MacBook-Pro  ~/Documents/msksidekick/2.0.8/08222023_173726/userobjects  ls
backup_admin.dat  backup_carlos.dat
 carlos.cuellar@Carlos-Alejandro-Cuellar-Macias-MacBook-Pro  ~/Documents/msksidekick/2.0.8/08222023_173726/userobjects  ls -lrth
total 16
-rw-r--r--  1 carlos.cuellar  staff   244B Aug 22 17:38 backup_admin.dat
-rw-r--r--  1 carlos.cuellar  staff   260B Aug 22 17:38 backup_carlos.dat
 carlos.cuellar@Carlos-Alejandro-Cuellar-Macias-MacBook-Pro  ~/Documents/msksidekick/2.0.8/08222023_173726/userobjects  cat backup_admin.dat
���}�(�userId�KuserName��admin��srcapiresponse�}�(�userId�KuserName�h� firstName���lastName�h �email��[hello@test.com](mailto:hello@test.com)��isAdmin���
                                                                                                                                  showWelcome���
userStatus��ACTIVE�� apiAccess��� principal�h password��
                                                                  Delphix-123�uu.%
 carlos.cuellar@Carlos-Alejandro-Cuellar-Macias-MacBook-Pro  ~/Documents/msksidekick/2.0.8/08222023_173726/userobjects  cat backup_carlos.dat
���}�(�userId�userName��carlos��srcapiresponse�}�(�userId�userName�h� firstName��carlos�lastName��carlos��email��[carlos@test.com](mailto:carlos@test.com)��isAdmin���
                                                                                                                                              showWelcome���
userStatus��ACTIVE�� apiAccess��� principal���password��
                                                              Delphix-123�uu.%
 carlos.cuellar@Carlos-Alejandro-Cuellar-Macias-MacBook-Pro  ~/Documents/msksidekick/2.0.8/08222023_173726/userobjects 

**Version**
2.0.8

**Comment by ajaytho** [comment]
Feature added in v2.0.8.5
