### ISSUE TITLE
msksidekick add-engine  -The script failed due to call depth overflow.

### ISSUE THREAD

**Issue by DavidReabow** [delphix/msksidekick#3]
I am running the following commands:

.\msksidekick add-engine -m 10.3.20.112 -t 64 -s 10
.\msksidekick add-engine -m 10.6.34.125  -t 64 -s 10

but keep getting this error:

The script failed due to call depth overflow.
    + CategoryInfo          : InvalidOperation: (0:Int32) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CallDepthOverflow

The Delphix engines are both 6.0.7
Both have 64GB memory  (is this what the "-t 64 " parameter is referring to?)
What is the "-s 10" parameter referring to? Is that memory required locally? 
Would I need to increase the memory settings in certain cases?

**Comment by DavidReabow** [comment]
This appears to be a powershell issue, the script runs when using cmd

**Comment by ajaytho** [comment]
Thanks for the update. Can I close this issue ?

**Comment by ajaytho** [comment]
No updates but issue seems to be self resolved.
