### ISSUE TITLE
$ ./msksidekick offline-backup-eng --mskengname x.y.z.z --backup_dir -->Error in MSK module 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ChrisQdb** [delphix/msksidekick#5]
** Expected Behavior**
Should start take backup

** Actual Behavior**
After directory created the backup failed with error:
Error in MSK module 'NoneType' object is not subscriptable

**Steps To Reproduce the Problem**
 ./msksidekick offline-backup-eng --mskengname x.y.z.z --backup_dir /oraadmin/tools/dxtoolkit2/msksidekick/msksidekickdir --username admin --password Admin_passwd--protocol http  

**Version**
v2.0.2

**Additional Context**
It works for another masking server

**Comment by ajaytho** [comment]
Can you please try latest version from develop branch or release Release v.2.0.2r1

**Comment by ChrisQdb** [comment]
The same error:
sername admin --password DDS@De1phix --protocol http

                                     Masking Sidekick - 2.0.2r1
****************************************************************************************************
Created directory structure for backups

Error in MSK module
'NoneType' object is not subscriptable

**Comment by ajaytho** [comment]
Please run in debug mode ( -d) as below. It will help to know where exactly its bailing out.
./msksidekick -d offline-backup-eng --mskengname x.y.z.z --backup_dir /oraadmin/tools/dxtoolkit2/msksidekick/msksidekickdir --username admin --password Admin_passwd--protocol http

**Comment by ChrisQdb** [comment]
Ajay,
Please see the output from the debug mode run:

                                     Masking Sidekick - 2.0.2r1
****************************************************************************************************
DEBUG: Created directory /tmp/_MEIRQrVXk/output
DEBUG: api_url = http:// x.y.z.z:80/masking/api/login
DEBUG: srcapikey=3a548a99-0f3d-4ca4-a3cd-0b5a9afb03f7
Created directory structure for backups

DEBUG: api_url = http:// x.y.z.z:80/masking/api/login
DEBUG: {"errorMessage":"Encountered internal server error, please see the logs for more details"}
Error in MSK module
'NoneType' object is not subscriptable

**Comment by ajaytho** [comment]
I think we have seen similar issue 
1) What is masking engine version ?
2) Was this engine anytime upgraded from previous version ? If yes what was previous version ?
3) Do you have custom mapplets installed in engine ?
4) Without using msksidekick, Can you try to export environment using delphix masking GUI ? If even this fails, then please open delphix support ticket mentioning export fails from masking GUI and refer only GUI functionality not working.

**Comment by ajaytho** [comment]
No further updates. Latest version is v2.0.8.5
